name: Test Functional

on:
  pull_request:
    branches: 
      - '**'

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome ./tests/fixture.js"