name: Functional Tests (recorder)

on:
  pull_request:
    branches: 
      - '**'

env:
  TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN: ${{ secrets.TESTCAFE_DASHBOARD_TOKEN }}

jobs:
  test:
    runs-on: [windows-2019]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
